fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Symfony\Component\Security\Core\User\User
  service:
    mailer: fos_user.mailer.noop
  from_email:
    address: "some@email.com"
    sender_name: "some name"