prooph_service_bus:

  event_buses:
    balance_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'

      router:
        type: 'prooph_service_bus.event_bus_router'
        routes: ~

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Prooph\EventStoreBusBridge\EventPublisher:
    arguments: ['@prooph_service_bus.balance_event_bus']
    public: true
    tags:
    - { name: 'prooph_event_store.balance_store.plugin' }