services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    #Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

    App\Twig\DumpHtmlExtension:
      tags:
        - { name: twig.extension }

    App\Twig\GetClassExtension:
      tags:
      - { name: twig.extension }
