fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  indexes:
    events:
      types:
        Calendar:
          persistence:
            driver:                 orm
            model:                  Calendar\View\CalendarView
            provider:               ~
            finder:                 ~
          properties:
            id:                     ~
            name:                   ~

        Calendar\Event:
          persistence:
            driver:                 orm
            model:                  Calendar\View\EventView
            provider:               ~
            finder:                 ~
          _parent:
            type:                   Calendar
            property:               calendar
            identifier:             id
          properties:
            id:                     ~
            expression:
              type:                 nested
              properties:
                after:
                  property_path:    start
                before:
                  property_path:    end
                dayOfWeek:
                  property_path:    start
                exactly:
                    property_path:  end
            timespan:
              type:                 nested
              properties:
                from:
                  property_path:    start
                to:
                  property_path:    end
