calendar.create:
  path: /calendar/{calendarId}
  controller: App\Controller\CalendarController::create
  methods: POST

calendar.get:
  path: /calendar/{calendarId}
  controller: App\Controller\CalendarController::getCalendar
  methods: GET

calendar.list:
  path: /calendar
  controller: App\Controller\CalendarController::list
  methods: GET

event.create:
  path: /calendar/{calendarId}/event
  controller: App\Controller\EventController::create
  methods: POST

event.all:
  path: /calendar/{calendarId}/event
  controller: App\Controller\EventController::events
  methods: GET

event.search:
    path: /events/search
    controller: App\Controller\EventController::search
#    options:
#      expose: true
#
#addEvent:
#    path: /add-event
#    controller: App\Controller\DefaultController::addEventAction
#    options:
#      expose: true
#
#updateEvent:
#    path: /update-event/{eventId}
#    controller: App\Controller\DefaultController::updateEventAction
#    options:
#      expose: true