calendar.create:
  path: /calendar/{calendarId}
  controller: App\Controller\CalendarController::create
  methods: POST

calendar.get:
  path: /calendar/{calendarId}
  controller: App\Controller\CalendarController::getCalendar
  methods: GET

calendar.list:
  path: /calendar
  controller: App\Controller\CalendarController::list
  methods: GET

event.create:
  path: /calendar/{calendarId}/event
  controller: App\Controller\EventController::create
  methods: POST

event.get:
  path: /calendar/{calendarId}/event
  controller: App\Controller\EventController::getEvent
  methods: GET

#
#index:
#    path: /
#    controller: App\Controller\DefaultController::indexAction
#
#getEvents:
#    path: /get-events
#    controller: App\Controller\DefaultController::getEventsAction
#    options:
#      expose: true
#
#addEvent:
#    path: /add-event
#    controller: App\Controller\DefaultController::addEventAction
#    options:
#      expose: true
#
#updateEvent:
#    path: /update-event/{eventId}
#    controller: App\Controller\DefaultController::updateEventAction
#    options:
#      expose: true