index:
    path: /
    controller: App\Controller\DefaultController::indexAction

getEvents:
    path: /get-events
    controller: App\Controller\DefaultController::getEventsAction
    options:
      expose: true

addEvent:
    path: /add-event
    controller: App\Controller\DefaultController::addEventAction
    options:
      expose: true

updateEvent:
    path: /update-event/{eventId}
    controller: App\Controller\DefaultController::updateEventAction
    options:
      expose: true